importing Libraries

In [11]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

importing Data Sets

In [12]:
ipl = pd.read_csv('C:\\Users\\Malik Gee\\Desktop\\Pandas For DataScience\\02_Pandas_DataFrame\\Data_Sets\\ipl-matches.csv')
movies = pd.read_csv('C:\\Users\\Malik Gee\\Desktop\\Pandas For DataScience\\02_Pandas_DataFrame\\Data_Sets\\movies.csv')

__Filtering a DataFrame__

Find all the final winners.

In [13]:
mask = ipl['MatchNumber'] == 'Final'
new_df = ipl[mask]
new_df[['Season','WinningTeam']]

# OR 

ipl[ipl['MatchNumber']=='Final'][['Season','WinningTeam']]

      Season            WinningTeam
0       2022         Gujarat Titans
74      2021    Chennai Super Kings
134  2020/21         Mumbai Indians
194     2019         Mumbai Indians
254     2018    Chennai Super Kings
314     2017         Mumbai Indians
373     2016    Sunrisers Hyderabad
433     2015         Mumbai Indians
492     2014  Kolkata Knight Riders
552     2013         Mumbai Indians
628     2012  Kolkata Knight Riders
702     2011    Chennai Super Kings
775  2009/10    Chennai Super Kings
835     2009        Deccan Chargers
892  2007/08       Rajasthan Royals

How many super over finishes have occured.

In [14]:
ipl[ipl['SuperOver'] == 'Y'].shape[0]

14

How many matches has csk won in kolkata.

In [15]:
ipl[(ipl['City'] == 'Kolkata') & (ipl['WinningTeam'] == 'Chennai Super Kings')].shape[0]

5

Toss winner is match winner in percentage.

In [16]:
(ipl[ipl['TossWinner'] == ipl['WinningTeam']].shape[0]/ipl.shape[0])*100

51.473684210526315

movies with rating heigher than 8 and votes is heigher than 10000.

In [17]:
movies[(movies['imdb_rating'] > 8) & (movies['imdb_votes'] > 10000)].shape[0]

43

Action movies with rating heigher than 7.5.

In [18]:
action = movies['genres'].str.split('|').apply(lambda x:'Action' in x)
rating = movies['imdb_rating'] > 7.5
movies[action & rating].shape[0]

33

Write a function that can return the track record of 2 teams against eachother.

In [19]:
def track_record(ipl,x,y):
    match_filter = ((ipl['Team1'] == x) & (ipl['Team2'] == y)) | ((ipl['Team1'] == y) & (ipl['Team2'] == x))
    h2h = ipl[match_filter]
    
    total_matches = len(h2h)
    
    if total_matches == 0:
        return f"No matches found between {x} and {y}."
    
    team1_wins = (h2h['WinningTeam'] == x).sum()
    team2_wins = (h2h['WinningTeam'] == y).sum()
    no_result = total_matches - (team1_wins + team2_wins)
    
    
    stats = {
        'Total Matches': total_matches,
        f'{x} Wins': team1_wins,
        f'{y} Wins': team2_wins,
        'No Result / Ties': no_result,
        f'{x} Win %': round((team1_wins / total_matches) * 100, 2)
    }
    
    return stats

In [20]:
track_record(ipl,'Royal Challengers Bangalore','Rajasthan Royals')

{'Total Matches': 27,
 'Royal Challengers Bangalore Wins': np.int64(13),
 'Rajasthan Royals Wins': np.int64(12),
 'No Result / Ties': np.int64(2),
 'Royal Challengers Bangalore Win %': np.float64(48.15)}

Adding new col to the dataframe.

In [22]:
movies['country'] = 'India'
movies.head(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date,country
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA),India
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India),India

From the existing ones.

In [26]:
#movies['actors'].str.split('|').apply(lambda x:x[0])

movies.dropna(inplace=True)

In [28]:
movies['lead actor'] = movies['actors'].str.split('|').apply(lambda x:x[0])

In [30]:
movies.head(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date,country,lead actor
11,Gully Boy,tt2395469,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Gully_Boy,Gully Boy,Gully Boy,0,2019,153,Drama|Music,8.2,22440,"Gully Boy is a film about a 22-year-old boy ""M...",A coming-of-age story based on the lives of st...,Apna Time Aayega!,Ranveer Singh|Alia Bhatt|Siddhant Chaturvedi|V...,6 wins & 3 nominations,14 February 2019 (USA),India,Ranveer Singh
34,Yeh Hai India,tt5525846,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Hai_India,Yeh Hai India,Yeh Hai India,0,2017,128,Action|Adventure|Drama,5.7,169,Yeh Hai India follows the story of a 25 years...,Yeh Hai India follows the story of a 25 years...,A Film for Every Indian,Gavie Chahal|Mohan Agashe|Mohan Joshi|Lom Harsh|,2 wins & 1 nomination,24 May 2019 (India),India,Gavie Chahal