In [2]:
import numpy as np
import pandas as pd

Data Sets

In [ ]:
subs = pd.read_csv('C:\\Users\\Malik Gee\\Desktop\\Pandas For DataScience\\Pandas_Series\\Data_Sets\\subs.csv').squeeze(True)
vk = pd.read_csv('C:\\Users\\Malik Gee\\Desktop\\Pandas For DataScience\\Pandas_Series\\Data_Sets\\kohli_ipl.csv',index_col='match_no').squeeze(True)
movies = pd.read_csv('C:\\Users\\Malik Gee\\Desktop\\Pandas For DataScience\\Pandas_Series\\Data_Sets\\bollywood.csv')

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

__Series Methods__

head and tail

In [53]:
print(subs.head())
print(subs.tail())

0    48
1    57
2    40
3    43
4    44
Name: Subscribers gained, dtype: int64
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, dtype: int64

sample

In [54]:
movies.sample(5)

                            movie                lead
1485  Talaash: The Hunt Begins...       Rakhee Gulzar
385            Dum Laga Ke Haisha  Ayushmann Khurrana
1058                  Apna Asmaan         Irrfan Khan
814          Ladies vs Ricky Bahl       Ranveer Singh
1198              Rang De Basanti          Aamir Khan

value counts

In [56]:
# har actor ne kitni movies ki hain (frequecy count)
movies.value_counts('lead')

lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Tanishaa Mukerji     1
Tanuja               1
Ankit                1
Rakhee Gulzar        1
Edwin Fernandes      1
Name: count, Length: 566, dtype: int64

sort values --> inplace

In [44]:
vk.sort_values('runs',ascending=False).head(1).values[0]

array([113])

sort index --> inplace

In [50]:
movies.sort_index()

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]